/** 工作台功能模块（与 PC 端 IDOMS 业务延伸） */
export const workbenchModules = [
  {
    key: 'todo',
    title: '待办任务',
    desc: '待处理事项汇总',
    icon: '📋',
    color: '#1677ff',
    path: '/pages/todo/index',
    placeholder: false,
    stub: true,
  },
  {
    key: 'qc-task',
    title: '质检任务',
    desc: '出厂质检 · 待检执行',
    icon: '✅',
    color: '#52c41a',
    path: '/pages/qc-task/list',
    placeholder: false,
  },
  {
    key: 'work-hours',
    title: '工时工资',
    desc: '报工与工资查询',
    icon: '⏱',
    color: '#fa8c16',
    path: '/pages/work-hours/index',
    placeholder: false,
    stub: true,
  },
  {
    key: 'approval',
    title: '审批管理',
    desc: '单据审批流转',
    icon: '📝',
    color: '#722ed1',
    path: '/pages/approval/index',
    placeholder: false,
    stub: true,
  },
  {
    key: 'material-req',
    title: '领料管理',
    desc: '领料申请与出库',
    icon: '📦',
    color: '#13c2c2',
    path: '/pages/material-req/index',
    placeholder: false,
    stub: true,
  },
]
